name: Run Azure Login PS
on: 
  workflow_dispatch:
permissions:
      id-token: write
      contents: write

jobs: 

  az-login-test-oidc:
    runs-on: ubuntu-latest
#     continue-on-error: true
    steps:
          
      - name: 'Azure PowerShell login with subscription'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENTID }}
          tenant-id: ${{ secrets.AZURE_TENANTID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTIONID }} 
          enable-AzPSSession: true
          
      - uses: azure/powershell@v1
        with:
          inlineScript: |
           Get-AzAccessToken
           Get-AzContext
          azPSVersion: "latest"
       
      - name: 'Introducing sleep'
        run: |
            echo "Hello there!"
            sleep 720
            echo "Oops! I fell asleep for 6 minutes!"
          
      - uses: azure/powershell@v1
        with:
          inlineScript: |
           Get-AzAccessToken
           Get-AzContext
          azPSVersion: "latest"
