name: Run Azure Login CLI
on: 
  workflow_dispatch:
permissions:
      id-token: write
      contents: write

jobs: 

  az-login-test-oidc:
    runs-on: ubuntu-latest
#     continue-on-error: true
    steps:
      - name: 'Az CLI login with subscription'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENTID }}
          tenant-id: ${{ secrets.AZURE_TENANTID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTIONID }} 
      
      - run: |
          az account show
          az account get-access-token
          
      - name: 'Introducing sleep'
        run: |
            echo "Hello there!"
            sleep 60
            echo "Oops! I fell asleep for 6 minutes!"
       
       
      - run: |
          az account show
          az account get-access-token
#          az webapp list
          
#       - name: 'Az CLI login without subscription'
#         uses: azure/login@v1
#         with:
#           client-id: ${{ secrets.AZURE_CLIENTID }}
#           tenant-id: ${{ secrets.AZURE_TENANTID }}
#           allow-no-subscriptions: true
          
#       - run: |
#           az account show
          
#       - name: 'Azure PowerShell login with subscription'
#         uses: azure/login@v1
#         with:
#           client-id: ${{ secrets.AZURE_CLIENTID }}
#           tenant-id: ${{ secrets.AZURE_TENANTID }}
#           subscription-id: ${{ secrets.AZURE_SUBSCRIPTIONID }} 
#           enable-AzPSSession: true
       
      - name: 'Introducing sleep'
        run: |
            echo "Hello there!"
            sleep 4
            echo "Oops! I fell asleep for 6 minutes!"
          
#       - uses: azure/powershell@v1
#         with:
#           inlineScript: |
#            Get-AzAccessToken
#            Get-AzContext
#           azPSVersion: "latest"
          
#       - name: 'Azure PowerShell login without subscription'
#         uses: azure/login@v1
#         with:
#           client-id: ${{ secrets.AZURE_CLIENTID }}
#           tenant-id: ${{ secrets.AZURE_TENANTID }}
#           enable-AzPSSession: true
#           allow-no-subscriptions: true
        
#       - uses: azure/powershell@v1
#         with:
#           inlineScript: "Get-AzContext"
#           azPSVersion: "latest"
          
  
